-- Generated by Atlas CE (atlas migrate diff), then hand-guarded once:
-- production and existing branches already hold this enum from the former
-- db/objects/01_types replay; the type is now owned by the desired state
-- (db/schema/schema.hcl). A migration that has never applied may be edited.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE "public"."order_status" AS ENUM ('new', 'shipped', 'cancelled');
  END IF;
END $$;
