#!/usr/bin/env bash
# CANONICAL SOURCE: github.com/Pbash-js/lakebase-accelerator -> scripts/deploy_db.sh
# Do NOT edit this file in a copy. Change it here, then propagate to consumers.
#
# Lakebase deploy: mint OAuth credential -> migrations -> objects -> rbac -> tests.
#
# Branch safety (hard rule): deploy_db.sh NEVER targets production from a
# developer terminal. Interactive runs deploy to a personal dev branch —
# created off production (7-day TTL) if it doesn't exist. Production is
# reachable ONLY inside GitHub Actions CD (cd-promotion, GITHUB_ACTIONS=true
# and TARGET_BRANCH=production set by the workflow).
#
# Env vars: LAKEBASE_PROJECT and DATABRICKS_PG_USER are prompted for when
# missing in an interactive session; CI must set them (hard fail otherwise).
#
# Auth: local `databricks auth login` profile, or DATABRICKS_HOST + DATABRICKS_TOKEN in CI.
set -euo pipefail

INTERACTIVE=0
if [ -t 0 ]; then INTERACTIVE=1; fi

# --- branch resolution ------------------------------------------------------
if [ -n "${TARGET_BRANCH:-}" ]; then
  if [ "$TARGET_BRANCH" = "production" ] && [ "${GITHUB_ACTIONS:-}" != "true" ]; then
    echo "✗ refusing to deploy to production outside GitHub Actions CD." >&2
    echo "  Production deploys happen only via cd-promotion (merge to main)." >&2
    echo "  Locally, run without TARGET_BRANCH to deploy to a dev branch." >&2
    exit 1
  fi
else
  if [ "$INTERACTIVE" != 1 ]; then
    echo "✗ TARGET_BRANCH not set in a non-interactive session — CI must set it explicitly." >&2
    exit 1
  fi
  _DEFAULT="dev-$(whoami | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9' | cut -c1-12)-$(date +%Y%m%d)"
  read -r -p "Target branch [${_DEFAULT}]: " _TB || _TB=""
  TARGET_BRANCH="${_TB:-$_DEFAULT}"
fi
if ! [[ "$TARGET_BRANCH" =~ ^[a-z][a-z0-9-]{0,62}$ ]]; then
  echo "Invalid branch id '$TARGET_BRANCH': 1-63 chars, lowercase start, lowercase/numbers/hyphens" >&2; exit 1
fi

# --- env vars: prompt interactively, fail hard in CI -----------------------
if [ -z "${LAKEBASE_PROJECT:-}" ]; then
  if [ "$INTERACTIVE" = 1 ]; then
    read -r -p "Lakebase project id (e.g. core-app-db): " LAKEBASE_PROJECT
  fi
  : "${LAKEBASE_PROJECT:?set LAKEBASE_PROJECT (the Lakebase project id, e.g. from databricks.yml)}"
fi
if [ -z "${DATABRICKS_PG_USER:-}" ]; then
  if [ "$INTERACTIVE" = 1 ]; then
    read -r -p "Lakebase Postgres role (e.g. your email): " DATABRICKS_PG_USER
  fi
  : "${DATABRICKS_PG_USER:?set DATABRICKS_PG_USER (your Lakebase Postgres role, e.g. your email)}"
fi

# --- preflight: fail fast with actionable messages, before touching anything
PREFLIGHT_FAIL=0
if ! databricks current-user me -o json >/dev/null 2>&1; then
  echo "✗ Databricks CLI not authenticated — run: databricks auth login"
  PREFLIGHT_FAIL=1
fi
[ "$PREFLIGHT_FAIL" = 0 ] || exit 1
echo "✓ preflight ok (authed via CLI; project: $LAKEBASE_PROJECT)"

trap 'echo "❌ deploy failed (line $LINENO). If auth was the problem: databricks auth login. If the token expired: re-run." >&2' ERR

# --- dev branch: create off production (7-day TTL) if absent, wait ACTIVE --
# (mirrors scripts/new_sandbox.sh; skipped for CD's production target)
if [ "$TARGET_BRANCH" != "production" ]; then
  if databricks postgres get-branch "projects/${LAKEBASE_PROJECT}/branches/${TARGET_BRANCH}" -o json >/dev/null 2>&1; then
    echo "▶ branch ${TARGET_BRANCH} already exists — reusing"
  else
    echo "▶ creating dev branch ${TARGET_BRANCH} off production (7-day TTL)"
    databricks postgres create-branch "projects/${LAKEBASE_PROJECT}" "${TARGET_BRANCH}" \
      --json "{\"spec\":{\"source_branch\":\"projects/${LAKEBASE_PROJECT}/branches/production\",\"ttl\":\"604800s\"}}" >/dev/null
  fi
  for i in $(seq 1 30); do
    STATE="$(databricks postgres get-endpoint "projects/${LAKEBASE_PROJECT}/branches/${TARGET_BRANCH}/endpoints/primary" -o json \
      | python -c "import sys,json;print(json.load(sys.stdin)['status']['current_state'])" 2>/dev/null || true)"
    [ "$STATE" = "ACTIVE" -o "$STATE" = "IDLE" ] && break
    [ "$i" = "30" ] && { echo "Endpoint did not become ready in time" >&2; exit 1; }
    sleep 2
  done
fi

ENDPOINT="projects/${LAKEBASE_PROJECT}/branches/${TARGET_BRANCH}/endpoints/primary"
echo "▶ target: $TARGET_BRANCH  (project: $LAKEBASE_PROJECT)"
HOST="$(databricks postgres get-endpoint "$ENDPOINT" --output json | python -c "import sys,json;print(json.load(sys.stdin)['status']['hosts']['host'])")"
TOKEN="$(databricks postgres generate-database-credential "$ENDPOINT" --output json | python -c "import sys,json;print(json.load(sys.stdin)['token'])")"

cd "$(dirname "$0")/.."

echo "▶ 1/3 migrations (Atlas-native apply, exactly-once, atlas.sum + revision checksums)"
ATLAS_BIN="${ATLAS_BIN:-atlas}" ./scripts/apply_migrations_atlas.sh "${HOST}" "${DATABRICKS_PG_USER}" "${TOKEN}"

echo "▶ 2/3 objects (idempotent replay)"
python scripts/apply_objects.py \
  --host "${HOST}" --port 5432 --dbname databricks_postgres \
  --user "${DATABRICKS_PG_USER}" --password "${TOKEN}" \
  --sslmode require --objects-root db/objects

echo "▶ 3/3 rbac (idempotent replay)"
if [ -f scripts/apply_rbac.py ]; then
  python scripts/apply_rbac.py \
    --host "${HOST}" --port 5432 --dbname databricks_postgres \
    --user "${DATABRICKS_PG_USER}" --password "${TOKEN}" \
    --sslmode require --rbac-dir db/rbac
else
  echo "  no scripts/apply_rbac.py — skipped"
fi

if [ "${SKIP_TESTS:-}" = 1 ]; then
  echo "▶ SKIP_TESTS=1 — tests skipped"
elif [ -d db/tests ]; then
  echo "▶ tests"
  PGHOST="${HOST}" PGUSER="${DATABRICKS_PG_USER}" PGPASSWORD="${TOKEN}" \
    python -m pytest db/tests -q
else
  echo "▶ no db/tests directory — skipped"
fi

echo "✅ deployed to ${TARGET_BRANCH}"
